#!/usr/bin/env ansible-playbook
#
# dnf install ansible-core
# ansible-playbook --extra-vars "old_root=/mnt/1" <<this-file>>
#
# This is my personal Fedora setup.
#
# I usually install a new release with the root_fs on a fresh,
# dedicated LV, keeping the previous Fedora releases' root_fs
# around. After I boot into the fresh installation, I mount the
# previous root_fs onto /mnt/1 and pass that mountpoint as old_root to
# the Ansible playbook.

- hosts: localhost
  connection: local
  become: true
  tasks:

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

#    - name: Show facts available on the system
#      ansible.builtin.debug:
#        var: ansible_facts

    - name: Install dnf plugins
      ansible.builtin.dnf:
        name: dnf-plugins-core
        update_cache: yes
        state: present

    - name: Enable and start ssh server
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: yes

    - name: Create groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      loop:
       - { name: 'mp3', gid: 900 }
       - { name: 'phil', gid: 1001 }
       - { name: 'christine', gid: 1004 }
       - { name: 'quirin', gid: 1005 }

    - name: Extract previous password hashes
      ansible.builtin.shell: grep {{ item }} {{ old_root }}/etc/shadow | cut -f2 -d ":"
      register: pw_hashes
      loop: ["phil", "christine", "quirin"]
      changed_when: false
      when: old_root is defined

    - name: Ensure users exist (with password hashes)
      ansible.builtin.user:
        name: "{{ item.user }}"
        comment: "{{ item.comment }}"
        uid: "{{ item.uid }}"
        group: "{{ item.group }}"
        groups: "{{ item.groups }}"
        password: "{{ (pw_hashes.results | selectattr('item', 'equalto', item.user) | first).stdout }}"
        append: true
        state: present
      loop:
        - { user: 'phil', comment: 'Philipp Reisner', uid: 1001, group: 'phil', groups: 'phil,mp3,wheel' }
        - { user: 'christine', comment: 'Christine Berger', uid: 1004, group: 'christine', groups: 'christine,mp3,wheel' }
        - { user: 'quirin', comment: 'Quirin Berger', uid: 1005, group: 'quirin', groups: 'quirin,mp3' }
      when: old_root is defined and pw_hashes is defined and pw_hashes.results is defined

    - name: Ensure users exist
      ansible.builtin.user:
        name: "{{ item.user }}"
        comment: "{{ item.comment }}"
        uid: "{{ item.uid }}"
        group: "{{ item.group }}"
        groups: "{{ item.groups }}"
        append: true
        state: present
      loop:
        - { user: 'phil', comment: 'Philipp Reisner', uid: 1001, group: 'phil', groups: 'phil,mp3,wheel' }
        - { user: 'christine', comment: 'Christine Berger', uid: 1004, group: 'christine', groups: 'christine,mp3,wheel' }
        - { user: 'quirin', comment: 'Quirin Berger', uid: 1005, group: 'quirin', groups: 'quirin,mp3' }
      when: not (old_root is defined and pw_hashes is defined and pw_hashes.results is defined)

    - name: Enable Fedora Copr Ubuntu fonts
      ansible.builtin.command:
        cmd: dnf copr enable atim/ubuntu-fonts --assumeyes
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:ubuntu-fonts.repo

    - name: Install ubuntu font
      ansible.builtin.dnf:
        name: ubuntu-family-fonts
        update_cache: yes
        state: present

    - name: Install dev tools 1
      ansible.builtin.dnf:
        name: ["emacs", "git", "git-email", "flex", "bison", "kernel-devel", "coccinelle",
               "clang-tools-extra", "bear", "autoconf", "automake", "keyutils-libs-devel",
               "clang" ]
        update_cache: yes
        state: present

    - name: Install dev tools 2
      ansible.builtin.dnf:
        name: ["openssl-devel-engine", "patch", "diffutils", "clitest", "asciidoctor", "po4a",
               "libaio-devel.x86_64", "ncurses-devel", "gcc-c++", "wireshark", "tcpdump",
               "strace", "ltrace", "pandoc"]
        update_cache: yes
        state: present

    - name: Generic tools
      ansible.builtin.dnf:
        name: ["mc", "htop", "nvtop", "console-setup", "mutt", "pwgen", "moreutils", "iproute-tc", "fio",
               "fish", "podman", "pylsp", "python3-pyOpenSSL", "pip", "virt-install", "virt-manager",
               "lnav", "lshw", "bsdtar"]
        update_cache: yes
        state: present

    - name: Applications
      ansible.builtin.dnf:
        name: ["gimp", "inkscape", "qgit", "xournal", "xournalpp",
               "libvirt-daemon-kvm", "libreoffice-langpack-de", "libvirt-nss", "v4l-utils",
               "waypipe", "vlc", "obs-studio", "plasma-nm-fortisslvpn", "libvirt-daemon-config-network",
               "dejavu-fonts-all"]
        update_cache: yes
        state: present

    - name: Install Google Chrome
      ansible.builtin.dnf:
        enablerepo: google-chrome
        name: google-chrome-stable
        state: present

    - name: Install latest Zoom client if not yet installed
      ansible.builtin.dnf:
        name: https://zoom.us/client/latest/zoom_x86_64.rpm
        state: present
        disable_gpg_check: yes
      when: "'zoom' not in ansible_facts.packages"

    - name: Create a symbolic link for consolefont
      ansible.builtin.file:
        src: /usr/share/consolefonts/Lat15-Terminus32x16.psf.gz
        dest: /usr/lib/kbd/consolefonts/Lat15-Terminus32x16.psf.gz
        owner: root
        group: root
        state: link

    - name: Set consolefont
      ansible.builtin.replace:
        path: /etc/vconsole.conf
        regexp: '^FONT=.*'
        replace: 'FONT=Lat15-Terminus32x16.psf.gz'
      register: consolefont_update

    - name: Activate consolefont
      ansible.builtin.service:
        name: systemd-vconsole-setup.service
        state: restarted
      when: consolefont_update.changed

    - name: Set default URI for virsh and libvirt
      ansible.builtin.replace:
        path: /etc/libvirt/libvirt.conf
        regexp: '^#uri_default.*'
        replace: 'uri_default = "qemu:///system"'

    - name: Create default storage pool for virsh and libvirt
      ansible.builtin.command:
        cmd: virsh pool-define-as --name default --type dir --target /var/lib/libvirt/images
        creates: /etc/libvirt/storage/default.xml

    - name: Autostart default storage pool for virsh and libvirt
      ansible.builtin.command:
        cmd: virsh pool-autostart default
        creates: /etc/libvirt/storage/autostart/default.xml

    - name: Configure NSS to resove virtual machines
      ansible.builtin.replace:
        path: /etc/nsswitch.conf
        regexp: 'mdns4_minimal \['
        replace: 'mdns4_minimal libvirt_guest ['

    - name: Add phil to libvirt group
      ansible.builtin.user:
        name: phil
        groups: libvirt
        append: true
        state: present

    - name: define VMs
      ansible.builtin.command:
        cmd: virsh define {{ item }}
        creates: /etc/libvirt/qemu/{{ item | basename }}
      with_fileglob: "{{ old_root }}/etc/libvirt/qemu/*.xml"
      when: old_root is defined

    - name: Create Mountpoints /mnt/1 /mnt/2
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
        state: directory
      loop:
        - { path: /mnt/1, mode: 'u=rwx,g=rx,o=rx' }
        - { path: /mnt/2, mode: 'u=rwx,g=rx,o=rx' }

# Do not use hostnames for the NFS server, as it can resolve to ipv6
    - name: NFS mounts for home network
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.path }}"
        fstype: nfs
        opts: rsize=8192,wsize=8192,timeo=14,user,soft
        state: "{{ 'present' if ansible_facts.form_factor in ['Notebook', 'Laptop'] else
                   ( 'mounted' if ansible_facts.form_factor == 'Desktop' else 'absent' ) }}"
        boot: "{{ ansible_facts.form_factor == 'Desktop' }}"
      loop:
        - { src: 192.168.0.7:/data, path: /data }
        - { src: 192.168.0.7:/home/christine, path: /home/base/christine }

    - name: Enable rpmfusion repos
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        disable_gpg_check: yes
      with_items:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"

    - name: Switch to full ffmpeg from rpmfusion
      ansible.builtin.command:
        cmd: dnf swap ffmpeg-free ffmpeg --allowerasing --assumeyes
      when: "'ffmpeg' not in ansible_facts.packages"

    - name: Check GPU type
      ansible.builtin.shell: lshw -class display -json | jq -r '.[].vendor'
      register: gpu_type
      changed_when: false

    - name: Switch to hardware codecs with AMD 1/4 from rpmfusion
      ansible.builtin.command:
        cmd: dnf swap mesa-va-drivers mesa-va-drivers-freeworld --assumeyes
      when: |
        gpu_type.stdout.startswith('Advanced Micro Devices') and (
        "mesa-va-drivers-freeworld" not in ansible_facts.packages or
        ansible_facts.packages["mesa-va-drivers-freeworld"] | selectattr('arch', 'equalto', 'x86_64') == [] )

    - name: Switch to hardware codecs with AMD 2/4 from rpmfusion
      ansible.builtin.command:
        cmd: dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld --assumeyes
      when: |
        gpu_type.stdout.startswith('Advanced Micro Devices') and (
        "mesa-vdpau-drivers-freeworld" not in ansible_facts.packages or
        ansible_facts.packages["mesa-vdpau-drivers-freeworld"] | selectattr('arch', 'equalto', 'x86_64') == [] )

    - name: Switch to hardware codecs with AMD 3/4 from rpmfusion
      ansible.builtin.command:
        cmd: dnf swap mesa-va-drivers.i686 mesa-va-drivers-freeworld.i686 --assumeyes
      when: |
        gpu_type.stdout.startswith('Advanced Micro Devices') and (
        "mesa-va-drivers-freeworld" not in ansible_facts.packages or
        ansible_facts.packages["mesa-va-drivers-freeworld"] | selectattr('arch', 'equalto', 'i686') == [] )

    - name: Switch to hardware codecs with AMD 4/4 from rpmfusion
      ansible.builtin.command:
        cmd: dnf swap mesa-vdpau-drivers.i686 mesa-vdpau-drivers-freeworld.i686 --assumeyes
      when: |
        gpu_type.stdout.startswith('Advanced Micro Devices') and (
        "mesa-vdpau-drivers-freeworld" not in ansible_facts.packages or
        ansible_facts.packages["mesa-vdpau-drivers-freeworld"] | selectattr('arch', 'equalto', 'i686') == [] )

    - name: Switch to hardware codecs with Intel from rpmfusion
      ansible.builtin.dnf:
        name: [ "intel-media-driver", "libva-intel-driver" ]
      when: |
        gpu_type.stdout == 'Intel Corporation'

    - name: Install Steam and v4l2loopback from rpmfusion
      ansible.builtin.dnf:
        name: ["steam", "kmod-v4l2loopback", "v4l2loopback", "obs-studio-plugin-x264"]
        state: present

    - name: Make Linux great again (disable CPU vulnerability mitigations)
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="(.*)(?<! mitigations=off)"$'
        replace: 'GRUB_CMDLINE_LINUX="\1 mitigations=off"'
      register: mitigations
      when: ansible_facts.form_factor in ['Notebook', 'Laptop', 'Desktop']

    - name: Find swap partition
      ansible.builtin.shell: lsblk --noheadings -o UUID $(grep -E -v "zram|Filename" /proc/swaps | cut -f 1 -d " ")
      register: swap_dev_uuid
      changed_when: false

    - name: Enable hibernate (suspend to disk)
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="(?!resume=)(.*)"$'
        replace: 'GRUB_CMDLINE_LINUX="resume=UUID={{ swap_dev_uuid.stdout }} \1"'
      register: enable_hibernate
      when: ansible_facts.form_factor in ['Notebook', 'Laptop', 'Desktop']

    - name: Enable resume from hibernation
      ansible.builtin.lineinfile:
        path: /etc/dracut.conf.d/resume.conf
        line: add_dracutmodules+=" resume "
        create: yes
      register: dracut_resume

    - name: Regenerate initramfs
      ansible.builtin.command:
        cmd: dracut --force
      when: dracut_resume.changed

    - name: Regenerate grub config after touching default/grub
      ansible.builtin.command:
        cmd: grub2-mkconfig -o /etc/grub2.cfg
      when: ansible_facts.form_factor in ['Notebook', 'Laptop', 'Desktop'] and ( mitigations.changed or enable_hibernate.changed )

    - name: Framework Laptop specifics repo
      ansible.builtin.command:
        cmd: dnf copr enable bsvh/fw-ectool --assumeyes
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:bsvh:fw-ectool.repo
      when: "ansible_facts.board_vendor == 'Framework'"

    - name: Framework Laptop firmware tool, and fingerprint reader support
      ansible.builtin.dnf:
        name: ["fw-ectool", "fprintd-pam", "fprintd"]
        update_cache: yes
        state: present
      when: "ansible_facts.board_vendor == 'Framework'"

    - name: Install Wireguard on Laptop
      ansible.builtin.dnf:
        name: wireguard-tools
        update_cache: yes
        state: present
      when: ansible_facts.form_factor in [ 'Notebook', 'Laptop' ]

    - name: Check WoL
      ansible.builtin.lineinfile:
        path: /etc/NetworkManager/system-connections/Kabelgebundene Verbindung 1.nmconnection
        regexp: '^wake-on-lan='
        state: absent
      check_mode: yes
      changed_when: false
      register: wake_on_lan
      when: ansible_facts.form_factor == 'Desktop'

    - name: Enable WoL
      ansible.builtin.command:
        cmd: nmcli connection modify "Kabelgebundene Verbindung 1" 802-3-ethernet.wake-on-lan magic
      when: ansible_facts.form_factor == 'Desktop' and "found" not in wake_on_lan

    - name: Get previous Wireguard config
      ansible.builtin.copy:
        src: "{{ old_root }}/etc/wireguard"
        dest: /etc/wireguard
        remote_src: true
      when: old_root is defined and ansible_facts.form_factor in [ 'Notebook', 'Laptop' ]

#    - name: Enable signal repo
#      ansible.builtin.command:
#        cmd: dnf config-manager addrepo --from-repofile=https://download.opensuse.org/repositories/network:im:signal/Fedora_Rawhide/network:im:signal.repo
#        creates: /etc/yum.repos.d/network:im:signal.repo

#    - name: Install signal-desktop
#      ansible.builtin.dnf:
#        name: ["signal-desktop"]
#        update_cache: yes
#        state: present


